php:
  preset: laravel
<<<<<<< HEAD
  enabled:
    - alpha_ordered_imports
  disabled:
    - length_ordered_imports
=======
  disabled:
>>>>>>> 29ff12519d03a6e3df07352a04477b84292c74fd
    - unused_use
  finder:
    not-name:
      - index.php
      - server.php
js:
  finder:
    not-name:
      - webpack.mix.js
css: true
